//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace People.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class P_Activity
    {
        public System.Guid aId { get; set; }
        public string aTitle { get; set; }
        public string aPlace { get; set; }
        public string aContent { get; set; }
        public Nullable<System.DateTime> aDatetime { get; set; }
        public Nullable<System.Guid> personId { get; set; }
    }
}
