//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace People.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class P_Class:IValidatableObject
    {
        public System.Guid cId { get; set; }
        public string cName { get; set; }
        public string cEnName { get; set; }
        public string cParentId { get; set; }
        public Nullable<int> cOrder { get; set; }
        public Nullable<int> cLevel { get; set; }

        /// <summary>
        /// 实现验证接口
        /// </summary>
        /// <param name="validationContext"></param>
        /// <returns></returns>
        public IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
        {
            P_Class single = validationContext.ObjectInstance as P_Class;
            
            if(single.cName==null)
            {
                yield return new ValidationResult("'cName'必须填写", new string[] { "cName" });
            }
            if(single.cEnName==null)
            {
                yield break;
            }
            if(single.cEnName!="zmm")
            {
                yield return new ValidationResult("'cEnName'必须是zmm", new string[] { "cEnName" });
            }
        }
    }
}
