//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace People.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class P_News
    {
        public System.Guid nId { get; set; }
        public string nForm { get; set; }
        public string nFormurl { get; set; }
        public string nAuthor { get; set; }
        public Nullable<System.Guid> uId { get; set; }
        public Nullable<System.DateTime> nTime { get; set; }
        public Nullable<int> nTalks { get; set; }
        public Nullable<int> nClicks { get; set; }
        public string nTitle { get; set; }
        public string nTitlepic { get; set; }
        public string nTips { get; set; }
        public string nContent { get; set; }
        public string nTags { get; set; }
        public string nLinkurl { get; set; }
        public Nullable<bool> nIsPage { get; set; }
        public Nullable<System.Guid> nClass1 { get; set; }
        public Nullable<short> nClass2 { get; set; }
        public Nullable<short> nStatus { get; set; }
        public Nullable<byte> nLevel { get; set; }
        public Nullable<bool> nIsRecommand { get; set; }
        public Nullable<bool> nIsDel { get; set; }
        public Nullable<System.Guid> personId { get; set; }
    }
}
