//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace People.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class P_Photo
    {
        public System.Guid pId { get; set; }
        public string pUrl { get; set; }
        public string pDesc { get; set; }
        public Nullable<System.DateTime> pAddTime { get; set; }
        public Nullable<System.Guid> AlbumId { get; set; }
    }
}
