//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace People.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;


    public partial class P_Tags : IDataErrorInfo
    {
        public System.Guid tId { get; set; }
        public string tName { get; set; }
        public Nullable<System.DateTime> tAddTime { get; set; }
        public Nullable<bool> tIsValid { get; set; }
        public Nullable<int> tClicks { get; set; }
        public Nullable<System.Guid> classId { get; set; }
        public Nullable<System.Guid> newsId { get; set; }

        public string Error
        {
            get
            {
                throw new NotImplementedException();
            }
        }

        public string this[string columnName]
        {
            get
            {
                switch (columnName)
                {
                    case "tName":
                        {
                            if (string.IsNullOrEmpty(this.tName))
                            {
                                return "'名称标签必须填写.'";
                            }
                            return null;
                        };
                    case "tAddTime":
                        {
                            if (string.IsNullOrEmpty(this.tName))
                            {
                                return "添加时间必须填写.";
                            }
                            return null;
                        }
                    default: return null;
                }
            }
        }
    }
}
