//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace People.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class P_Tags
    {
        public System.Guid tId { get; set; }
        public string tName { get; set; }
        public Nullable<System.DateTime> tAddTime { get; set; }
        public Nullable<bool> tIsValid { get; set; }
        public Nullable<int> tClicks { get; set; }
        public Nullable<System.Guid> classId { get; set; }
        public Nullable<System.Guid> newsId { get; set; }
    }
}
