//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace People.CreateModelsHelper
{
    using System;
    using System.Collections.Generic;
    
    public partial class P_AlbumInfo
    {
        public System.Guid aiId { get; set; }
        public string aiUrl { get; set; }
        public string aiDesc { get; set; }
        public Nullable<System.Guid> albumId { get; set; }
        public Nullable<System.DateTime> aiAddTime { get; set; }
    }
}
