//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace People.CreateModelsHelper
{
    using System;
    using System.Collections.Generic;
    
    public partial class P_Class
    {
        public System.Guid cId { get; set; }
        public string cName { get; set; }
        public string cEnName { get; set; }
        public string cParentId { get; set; }
        public Nullable<int> cOrder { get; set; }
        public Nullable<int> cLevel { get; set; }
    }
}
