//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace People.CreateModelsHelper
{
    using System;
    using System.Collections.Generic;
    
    public partial class P_Question
    {
        public System.Guid qId { get; set; }
        public string qTitle { get; set; }
        public string qAsker { get; set; }
        public Nullable<System.DateTime> qAddTime { get; set; }
        public Nullable<System.Guid> personId { get; set; }
        public Nullable<int> qClicks { get; set; }
    }
}
