//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace People.CreateModelsHelper
{
    using System;
    using System.Collections.Generic;
    
    public partial class P_User
    {
        public System.Guid uId { get; set; }
        public string uName { get; set; }
        public string uPwd { get; set; }
        public string uPhoto { get; set; }
        public Nullable<int> uAge { get; set; }
        public Nullable<bool> uSex { get; set; }
        public string uMobile { get; set; }
        public string uPhone { get; set; }
        public string uProvince { get; set; }
        public string uCity { get; set; }
        public string uZipCode { get; set; }
        public string uAddr { get; set; }
        public Nullable<System.DateTime> uLoginTime { get; set; }
    }
}
