//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace People.CreateModelsHelper
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_GetPersonList
    {
        public System.Guid pId { get; set; }
        public string pCnName { get; set; }
        public string pEnName { get; set; }
        public string pPenName { get; set; }
        public Nullable<bool> pSex { get; set; }
        public string pJob { get; set; }
        public string pNation { get; set; }
        public string ClassId { get; set; }
        public Nullable<System.DateTime> pAddTime { get; set; }
        public string cName { get; set; }
        public string cEnName { get; set; }
        public Nullable<int> cOrder { get; set; }
        public string pTips { get; set; }
        public string pPhoto { get; set; }
        public Nullable<int> pClicks { get; set; }
        public string pNationality { get; set; }
        public Nullable<System.DateTime> pBirthday { get; set; }
        public Nullable<decimal> pHeight { get; set; }
        public Nullable<decimal> pWeight { get; set; }
        public string pBWH { get; set; }
        public string pUniversity { get; set; }
        public string pHomeProvince { get; set; }
        public string pHomeCity { get; set; }
        public System.Guid cId { get; set; }
        public string cParentId { get; set; }
        public Nullable<int> cLevel { get; set; }
        public string pHomeArea { get; set; }
        public string pNowProvice { get; set; }
        public string pNowCity { get; set; }
        public string pNowArea { get; set; }
        public string pNowPlace { get; set; }
        public string pBloodType { get; set; }
        public string pSpeak { get; set; }
        public string pSinaBlog { get; set; }
        public string pTencentBlog { get; set; }
        public string pHomePage { get; set; }
        public string pIntroduce { get; set; }
    }
}
